### PR TITLE
fix cors issue in dev environment when accessing api.coingecko.com

### LINKED ISSUE #7: CORS issue of accessing `api.coingecko.com`
## Issue Overview

In dev environment, run nextjs app locally, will cause CORS issue, when access `https://api.coingecko.com/api/v3/simple/price` endpoint.

## Proposed Solutions or Ideas

Move the api call to nextjs servers side, and in frontend, just access: `/api/price/${symbol}`

### PR DESCRIPTION
**Pull request by iossocket**
# Fix cors issue when accessing api.coingecko.com

Fixes #7 

## Types of change

- [ ] Feature
- [ ] Bug
- [x] Enhancement

## Comments (optional)
we can l leverage next.js api feature more

### CODE REVIEW

**Review by 0xquantum3labs — APPROVED** [review]

**Comment by 0xquantum3labs** [comment]
approving this, i think we should implement caching and the same fix on `scaffold-stark-2` wdyt @iossocket ?

**Comment by iossocket** [comment]
Hi @0xquantum3labs, you are right, the fix should be applied to main repo as well.
I have two questions: 
1. api.coingecko.com response is a pricing data, it should be kind of realtime data, do we need cache it? 
2. we duplicate codes in these two repos, do we have a plan to extract them to a separate lib?
thanks

**Comment by 0xquantum3labs** [comment]
@iossocket thanks for the feedback:
1. i think this api has a limit for being used, we can use a cache to protect this limit
2. good point, in order to make this easy to maintain based on the other 2 repos, we can consider keeping both for now. later we might think of a better way when the repo is more robust

**Comment by iossocket** [comment]
@0xquantum3labs thanks for your reply and explanation, I will add cache for this api call later and apply the change to main repo as well.

**Pull request merged**
